# Site settings
title: "Desenvolvimento de Software e Tecnologia"
email: desenvolvimento@gsd.com.br
description: > # this means to ignore newlines until "baseurl:"
  Avant é uma empresa do grupo sobranselhas design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:
email: 
facebook_username: avantsd
twitter_username:
github_username: AvantSD
address: 
  - line: R. Lídia Brígido, 55 
  - line: Parque Manibura, Fortaleza - CE
  - line: CEP 60821-795  
  # Feel free to add more lines here 
telephone: (85) 3036-9051
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown